//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICafeWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomersMaster
    {
        public CustomersMaster()
        {
            this.OrdersMasters = new HashSet<OrdersMaster>();
        }
    
        public int CustomerId { get; set; }
        public string CustomerName { get; set; }
        public string CustomerEmailId { get; set; }
        public string CustomerPhone { get; set; }
        public string CustomerDescription { get; set; }
        public string CustomerAddress { get; set; }
    
        public virtual ICollection<OrdersMaster> OrdersMasters { get; set; }
    }
}
