//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICafeWebAPI
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ICafeDBEntities : DbContext
    {
        public ICafeDBEntities()
            : base("name=ICafeDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CustomersMaster> CustomersMasters { get; set; }
        public DbSet<ItemCategoriesMaster> ItemCategoriesMasters { get; set; }
        public DbSet<ItemsMaster> ItemsMasters { get; set; }
        public DbSet<MenusMaster> MenusMasters { get; set; }
        public DbSet<OrdersMaster> OrdersMasters { get; set; }
        public DbSet<PermissionsMaster> PermissionsMasters { get; set; }
        public DbSet<RolesMaster> RolesMasters { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<UsersMaster> UsersMasters { get; set; }
    }
}
