//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICafeWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemCategoriesMaster
    {
        public int ItemCategoryId { get; set; }
        public string ItemCategoryName { get; set; }
        public string ItemCategoryDescription { get; set; }
        public Nullable<decimal> ItemCategoryDiscount { get; set; }
    }
}
