//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICafeWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdersMaster
    {
        public int OrderId { get; set; }
        public Nullable<int> TotalReOrders { get; set; }
        public string PaymentStatus { get; set; }
        public int UserId { get; set; }
        public int CustomerId { get; set; }
    
        public virtual CustomersMaster CustomersMaster { get; set; }
        public virtual UsersMaster UsersMaster { get; set; }
    }
}
