//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICafeWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class RolesMaster
    {
        public RolesMaster()
        {
            this.UsersMasters = new HashSet<UsersMaster>();
        }
    
        public int RoleId { get; set; }
        public string RoleName { get; set; }
        public string RoleDescription { get; set; }
        public Nullable<int> PermissionId { get; set; }
    
        public virtual PermissionsMaster PermissionsMaster { get; set; }
        public virtual ICollection<UsersMaster> UsersMasters { get; set; }
    }
}
