//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICafeWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersMaster
    {
        public UsersMaster()
        {
            this.OrdersMasters = new HashSet<OrdersMaster>();
        }
    
        public int UserId { get; set; }
        public string UserName { get; set; }
        public string UserDescription { get; set; }
        public string UserPassword { get; set; }
        public Nullable<int> RoleId { get; set; }
    
        public virtual ICollection<OrdersMaster> OrdersMasters { get; set; }
        public virtual RolesMaster RolesMaster { get; set; }
    }
}
