//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICafeWebAPI.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_Devices
    {
        public M_Devices()
        {
            this.M_Tables = new HashSet<M_Tables>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public bool IsMultipleMode { get; set; }
    
        public virtual ICollection<M_Tables> M_Tables { get; set; }
    }
}
