//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICafeWebAPI.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_Orders
    {
        public int Id { get; set; }
        public Nullable<int> TotalReOrders { get; set; }
        public string PaymentStatus { get; set; }
        public string UserId { get; set; }
        public int CustomerId { get; set; }
    
        public virtual M_Customers M_Customers { get; set; }
        public virtual M_Users M_Users { get; set; }
    }
}
