//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICafeWebAPI.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_Permissions
    {
        public M_Permissions()
        {
            this.M_Roles = new HashSet<M_Roles>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<M_Roles> M_Roles { get; set; }
    }
}
