//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICafeWebAPI.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_Roles
    {
        public M_Roles()
        {
            this.M_Users = new HashSet<M_Users>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<int> PermissionId { get; set; }
    
        public virtual M_Permissions M_Permissions { get; set; }
        public virtual ICollection<M_Users> M_Users { get; set; }
    }
}
