//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICafeWebAPI.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_Tables
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> DeviceID { get; set; }
    
        public virtual M_Devices M_Devices { get; set; }
    }
}
