//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICafeWebAPI.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_Users
    {
        public M_Users()
        {
            this.M_Orders = new HashSet<M_Orders>();
        }
    
        public string Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Password { get; set; }
        public Nullable<int> RoleId { get; set; }
    
        public virtual ICollection<M_Orders> M_Orders { get; set; }
        public virtual M_Roles M_Roles { get; set; }
    }
}
